[versions]
kotlin              = "2.4.0"
agp                 = "8.13.0"
compose             = "1.12.0"
media3              = "1.11.0"
coil                = "3.3.0"
coroutines          = "1.10.2"
lifecycle           = "2.9.4"
activityCompose     = "1.11.0"
palette             = "1.0.0"
javafx              = "21.0.4"
jaudiotagger        = "3.0.1"
guava               = "33.4.0-android"
androidMinSdk       = "24"
androidTargetSdk    = "36"
androidCompileSdk   = "36"

[libraries]
kotlinx-coroutines-core    = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-swing   = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session   = { module = "androidx.media3:media3-session",   version.ref = "media3" }
media3-common    = { module = "androidx.media3:media3-common",    version.ref = "media3" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication  = { id = "com.android.application", version.ref = "agp" }
composeMultiplatform= { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler     = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
